version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 302590777472.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=302590777472.dkr.ecr.us-east-1.amazonaws.com/udacity-analytics-docker
  build:
    commands:
      - echo Starting build at `date`
      - echo Building the Docker image...
      - docker build -t udacity-analytics-docker:test-coworking-analytics analytics/
      - docker tag udacity-analytics-docker:test-coworking-analytics $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
      - docker tag udacity-analytics-docker:test-coworking-analytics $REPOSITORY_URI:test-coworking-analytics
  post_build:
    commands:
      - echo Completed build at `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
      - docker push $REPOSITORY_URI:test-coworking-analytics